// Swagger Schemas
// this can generated by swagger-typescript-api package

export type Task = {
  id: string;
  text: string;
  completed: boolean;
  createdDate: number;
  completedDate: number;
}

export type CreateTask = {
  text: string;
}

export type UpdateTask = {
  text: string;
}